[versions]
# AS releases: https://plugins.jetbrains.com/docs/intellij/android-studio-releases-list.html
# IC sources: https://www.jetbrains.com/intellij-repository/releases
# choose a matching/similar build

ideaVersion = "231.9423.9" # AS Hedgehog | 2023.1.1
kotlin = "2.0.10"

[libraries]
intellijCoreImpl = { module = "com.jetbrains.intellij.platform:core-impl", version.ref = "ideaVersion" }
intellijProjectModelImpl = { module = "com.jetbrains.intellij.platform:project-model-impl", version.ref = "ideaVersion" }
intellijAnalysisImpl = { module = "com.jetbrains.intellij.platform:analysis-impl", version.ref = "ideaVersion" }
intellijIndexing = { module = "com.jetbrains.intellij.platform:indexing", version.ref = "ideaVersion" }
intellijUtilUi = { module = "com.jetbrains.intellij.platform:util-ui", version.ref = "ideaVersion" }
coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1"

junit = "junit:junit:4.13.2"
truth = "com.google.truth:truth:1.4.4"

[bundles]
intelliJ = ["intellijCoreImpl", "intellijProjectModelImpl", "intellijAnalysisImpl", "intellijIndexing", "intellijUtilUi"]

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
grammarKitComposer = { id = "com.alecstrong.grammar.kit.composer", version = "0.1.12" }
spotless = { id = "com.diffplug.spotless", version = "6.25.0" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.28.0" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
intellij = { id = "org.jetbrains.intellij", version = "1.17.4" }
